# Generated by Django 6.0.1 on 2026-01-16 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sponsors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "title_en",
                    models.CharField(
                        blank=True, help_text="English title", max_length=255, null=True
                    ),
                ),
                ("subtitle", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "subtitle_en",
                    models.CharField(
                        blank=True,
                        help_text="English subtitle",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="events/"),
                ),
                (
                    "date",
                    models.CharField(
                        help_text="Date string format, e.g., '20.07.2025 - 23.07.2025'",
                        max_length=100,
                    ),
                ),
                ("date_range", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ended", "Ended"),
                            ("closed", "Registration Closed"),
                            ("open", "Registration Open"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "status_text",
                    models.CharField(
                        blank=True,
                        help_text="Status text (can be translated on frontend)",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "description_en",
                    models.TextField(
                        blank=True, help_text="English description", null=True
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "registration_url",
                    models.URLField(
                        blank=True,
                        help_text="Registration/Event URL (for the register button)",
                        null=True,
                    ),
                ),
                ("organizer", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sponsors",
                    models.ManyToManyField(
                        blank=True, related_name="events", to="sponsors.sponsor"
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="events/gallery/")),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order (lower numbers first)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Image",
                "verbose_name_plural": "Event Images",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
