# Generated by Django 6.0.1 on 2026-01-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="order",
            field=models.IntegerField(
                default=0,
                help_text="Manual order number (lower numbers appear first). Only used when ordering_type is 'Manual Order'",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="ordering_type",
            field=models.CharField(
                choices=[("manual", "Manual Order"), ("date", "Sort by Date")],
                default="date",
                help_text="Choose 'Manual Order' to use custom order field, or 'Sort by Date' to automatically sort by date",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="organizer_logo",
            field=models.ImageField(
                blank=True,
                help_text="Organizer logo. If not provided, will use default TSAK logo.",
                null=True,
                upload_to="events/organizers/",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.CharField(
                help_text="Date string format, e.g., '20.07.2025 - 23.07.2025' or '20.07.2025'",
                max_length=100,
            ),
        ),
    ]
