# Generated by Django 6.0.1 on 2026-01-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("logo", models.ImageField(upload_to="sponsors/logos/")),
                ("description", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("embassy", "Embassy"),
                            ("partner", "Partner"),
                            ("network", "Network"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order (lower numbers first)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sponsor",
                "verbose_name_plural": "Sponsors",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
