# Generated by Django 6.0.1 on 2026-01-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="Description (English)"),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Name (English)"
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="type",
            field=models.CharField(
                choices=[
                    ("embassy", "Embassy"),
                    ("partner", "Partner"),
                    ("network", "Network"),
                    ("sponsor", "Sponsor"),
                ],
                max_length=20,
            ),
        ),
    ]
