# Generated by Django 6.0.1 on 2026-01-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name (Thai)")),
                (
                    "provider",
                    models.CharField(max_length=255, verbose_name="Provider (Thai)"),
                ),
                ("description", models.TextField(verbose_name="Description (Thai)")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Name (English)"
                    ),
                ),
                (
                    "provider_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Provider (English)"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (English)"),
                ),
                ("benefits", models.JSONField(default=list)),
                ("benefits_en", models.JSONField(default=list)),
                (
                    "deadline",
                    models.CharField(max_length=255, verbose_name="Deadline (Thai)"),
                ),
                (
                    "deadline_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Deadline (English)"
                    ),
                ),
                ("eligibility", models.TextField(verbose_name="Eligibility (Thai)")),
                (
                    "eligibility_en",
                    models.TextField(blank=True, verbose_name="Eligibility (English)"),
                ),
                (
                    "monthly_allowance",
                    models.CharField(
                        max_length=100, verbose_name="Monthly Allowance (Thai)"
                    ),
                ),
                (
                    "monthly_allowance_en",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Monthly Allowance (English)",
                    ),
                ),
                ("link", models.URLField(max_length=500)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("government", "Government"),
                            ("university", "University"),
                            ("private", "Private"),
                            ("organization", "Organization"),
                        ],
                        max_length=20,
                    ),
                ),
                ("funding_type", models.JSONField(default=list)),
                ("study_level", models.JSONField(default=list)),
                ("field_of_study", models.JSONField(default=list)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Scholarship",
                "verbose_name_plural": "Scholarships",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
