# Generated by Django 6.0.1 on 2026-01-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                (
                    "picture",
                    models.ImageField(blank=True, null=True, upload_to="members/"),
                ),
                ("university", models.CharField(max_length=200)),
                ("major", models.CharField(max_length=200)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("president", "President"),
                            ("vice_president", "Vice President"),
                            ("secretary", "Secretary"),
                            ("head", "Head"),
                            ("member", "Member"),
                            ("advisor", "Advisor"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("honorary", "Honorary"),
                            ("executive", "Executive"),
                            ("liaison", "Liaison"),
                            ("pr", "Public Relations"),
                            ("events", "Events"),
                            ("accounting", "Accounting"),
                            ("documents", "Documents"),
                            ("it", "IT Support"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "working",
                    models.BooleanField(
                        default=True, help_text="Is currently active member"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Member",
                "verbose_name_plural": "Members",
                "ordering": ["position", "lastname", "firstname"],
            },
        ),
    ]
